parameters:
#    vin_c2_c_user.example.class: VinC2C\UserBundle\Example

services:
    vinc2c_user.registration.form.type:
        class: VinC2C\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: vinc2c_user_registration }
#    vin_c2_c_user.example:
#        class: %vin_c2_c_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

