parameters:
#    vin_c2_c_landing_page.example.class: VinC2C\LandingPageBundle\Example

services:
#    vin_c2_c_landing_page.example:
#        class: %vin_c2_c_landing_page.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]