<?php

namespace VinC2C\LandingPageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OffreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreRepository extends EntityRepository {

    public function findAnnonceByParametres($data) {

        $query = $this->createQueryBuilder('a');

//        $query->Where('a.prix BETWEEN :prixMin AND :prixMax')
//                ->setParameters(array(
//                    'prixMin' => $data['prix'],
//                    'prixMax' => $data['prix_Max']));

        if ($data['prix'] != '') {
            $data_final = explode(",", $data['prix']);
            $prixMin = intval($data_final[0]);
            $prixMax = intval($data_final[1]);

            $query->Where('a.prix BETWEEN :prixMin AND :prixMax')
                    ->setParameters(array(
                        'prixMin' => $prixMin,
                        'prixMax' => $prixMax));
        }

// Si la recherche porte sur toutes les marques

        if ($data['couleur'] != '') {

            $query->andWhere('a.couleur = :couleur')
                    ->setParameter('couleur', $data['couleur']);
        }

// Si la recherche porte sur tout les modèles

        if ($data['millesime'] != '') {

            $query->andWhere('a.millesime = :millesime')
                    ->setParameter('millesime', $data['millesime']);
        }

// Si la recherche porte sur toutes les villes

        if ($data ['titre'] != '') {

            $query->andWhere('a.titre = :titre')
                    ->setParameter('titre', $data['titre']);
        }


        return $query->getQuery()->getResult();
    }

}
